- name: Apache demarre au demarrage
        service: name=apache2 state=started enabled=yes
--------------------------------

- name: Apache demarre au demarrage
        service:
          name: apache2
          state: started
          enabled: yes
--------------------------------
- hosts: webservers
  become: true
    tasks:
      - name: INSTALLATION SERVEURS WEB
        apt:
          name:
            - apache2
            - php
          state: present
      - name: Apache demarre au demarrage
        service:
          name: apache2
          state: started
          enabled: yes

